volumes:
  app-mysql: {
    name: app-mysql
  }
  app-redis: {
    name: app-redis
  }

networks:
  app-network:
    name: app-network
    ipam:
      driver: default
      config:
        - subnet: 11.1.0.0/16

services:
  app-web:
    container_name: app-web
    build:
      context: .
      dockerfile: dockerfiles/web-source.Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      app-network:
        ipv4_address: 11.1.1.1

  app-mysql:
    container_name: app-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    volumes:
      - app-mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      app-network:
        ipv4_address: 11.1.1.2
    restart: no

  app-redis:
    container_name: app-redis
    image: redis:7.4
    depends_on:
      - app-web
    volumes:
      - app-redis:/data
    networks:
      app-network:
        ipv4_address: 11.1.1.3
    ports:
      - '6379:6379'
    restart: no

